name: "Build the project" # Builds the project and archives the checkstyle results
on: [pull_request, push]

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout this repository"
        uses: actions/checkout@v2

      - name: "Setup Java 8"
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: "Make Gradle Wrapper executable"
        run: chmod +x ./gradlew

      - name: "Build with Gradle"
        run: ./gradlew build

      - name: "Archives Checkstyle results"
        uses: "actions/upload-artifact@v2"
        with:
          name: "test-results"
          path: |
            build/reports/
            build/libs